name: Validate JSON and Push to Master
permissions:
  contents: write
on:
  push:
    branches:
      - dev  # Triggers the action on push to the dev branch

jobs:
  validate_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository at the current (dev) branch
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Validate the JSON (resume.json against schema.json)
      - name: Validate resume.json against schema.json
        uses: dsanders11/json-schema-validate-action@v1.1.2
        with:
          schema: schema.json  # Path to the schema file
          files: resume.json    # Path to the JSON file you want to validate

      # Step 3: Push to master if validation is successful
      - name: Deploy to master
        if: success()
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'